matrix:
  include:
    - language: java
      jdk:
        - openjdk11
      branches:
        except:
          - gh-pages
      cache:
        directories:
          - "$HOME/.m2/repository"
      install: true
      script: mvn clean package -Drelease